# Generated by Django 5.1.1 on 2025-11-27 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('short_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('UNIT', 'NCC Unit'), ('GROUP', 'Group HQ'), ('DIRECTORATE', 'Directorate'), ('HQ_DGNCC', 'HQ DG NCC')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent HQ (e.g., Unit → Group HQ → Directorate → HQ DGNCC).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='recruitment.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='recruitment.servicebranch')),
            ],
            options={
                'ordering': ['branch', 'order', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. PI Staff (Army), CVDO (Contractual)', max_length=255)),
                ('description', models.TextField()),
                ('sanctioned_strength', models.PositiveIntegerField(default=1, help_text='Total sanctioned posts for this vacancy type at this organization.')),
                ('current_hired', models.PositiveIntegerField(default=0, help_text='Number of veterans already hired here.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_ranks', models.ManyToManyField(blank=True, help_text='If only certain ranks are allowed for this vacancy.', related_name='vacancies', to='recruitment.rank')),
                ('branch', models.ForeignKey(help_text='Service of veteran required for this vacancy.', on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='recruitment.servicebranch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='NCC Unit / Group / Dte where the veteran will be employed.', on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='recruitment.organization')),
            ],
            options={
                'ordering': ['-opening_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Veteran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(help_text='Service number / ADN equivalent', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('date_of_enrolment', models.DateField(blank=True, null=True)),
                ('date_of_discharge', models.DateField(blank=True, null=True)),
                ('total_service_years', models.PositiveIntegerField(blank=True, null=True)),
                ('last_unit_served', models.CharField(blank=True, max_length=255)),
                ('verification_status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING_VERIFICATION', max_length=30)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veterans', to='recruitment.servicebranch')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veterans', to='recruitment.rank')),
                ('user', models.OneToOneField(blank=True, help_text='Optional link to auth user (for candidate portal).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veteran_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['branch', 'rank__order', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_SCRUTINY', 'Under Scrutiny'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('RECOMMENDED', 'Recommended'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_updated', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.vacancy')),
                ('veteran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.veteran')),
            ],
            options={
                'ordering': ['-application_date'],
                'unique_together': {('veteran', 'vacancy')},
            },
        ),
    ]
